In [1]:
import pandas as pd
import os
import numpy as np
import cv2

In [8]:
df =pd.read_csv('data_labels.csv')
df

name  label  width  height  xmin  ymin  xmax  ymax
0  cats_000.jpg    cat    474     632   103    72   436   603
1  cats_007.jpg  cat-1    474     266   301    37   460   265
2  cats_050.jpg    cat    474     237   157    40   314   205
3  cats_072.jpg  cat-2    474     266   187     1   474   266
4  cats_076.jpg    cat    474     474    12     6   244   462
5  cats_079.jpg    cat    474     266    78     1   474   266
6  cats_088.jpg  cat-3    474     266   129     1   385   266
7  cats_091.jpg    cat    474     316   156    13   328   316
8  cats_099.jpg  cat-4    474     237   226     1   395   237
9  cats_100.jpg    cat    474     266    40     1   420   266

In [3]:
folder=input()

cat


In [13]:
dir='output2'
wd=os.getcwd()
folder_path=os.path.join(wd,folder) 

if not os.path.isdir(dir):
    os.mkdir(dir)
    

for index , row in df.iterrows():
    

     
    
    image_name=str(row['name'])
    name='output' + image_name
    image_name=folder_path + '\\' + image_name
    img=cv2.imread(image_name)
    print(img)
    pt1=(row['xmin'],row['ymin'])
    pt2=(row['xmax'],row['ymax'])
    color =(0,255,0)
    thickness=5
    
    img1=cv2.rectangle(img, pt1, pt2, color, thickness)
    img1 = cv2.putText(img1, row['label'], (row['xmin'], row['ymin']-10), cv2.FONT_HERSHEY_SIMPLEX, 1,(0,0,0), 2)
    
  
   
    if img1 is not None:
        cv2.imwrite(os.path.join(dir,name),img1)
    else:
        continue
        
        
        
    
    

    
    

[[[187 169 158]
  [187 169 158]
  [188 170 159]
  ...
  [215 197 186]
  [219 201 190]
  [219 201 190]]

 [[186 168 157]
  [186 168 157]
  [188 170 159]
  ...
  [213 195 184]
  [218 200 189]
  [218 200 189]]

 [[186 168 157]
  [186 168 157]
  [187 169 158]
  ...
  [211 193 182]
  [217 199 188]
  [217 199 188]]

 ...

 [[172 185 199]
  [185 201 214]
  [171 187 199]
  ...
  [234 241 244]
  [249 254 255]
  [248 253 255]]

 [[158 174 187]
  [174 191 204]
  [158 176 187]
  ...
  [238 245 248]
  [242 247 250]
  [241 246 249]]

 [[170 187 200]
  [176 193 206]
  [145 165 176]
  ...
  [248 255 255]
  [246 251 254]
  [245 250 253]]]
[[[155 162 171]
  [152 159 168]
  [149 156 165]
  ...
  [ 49  44 119]
  [ 33  27 104]
  [ 33  27 104]]

 [[154 161 170]
  [151 158 167]
  [148 155 164]
  ...
  [ 53  49 121]
  [ 29  24  99]
  [ 29  24  99]]

 [[152 159 168]
  [149 156 165]
  [146 153 162]
  ...
  [ 54  50 121]
  [ 39  35 106]
  [ 39  35 106]]

 ...

 [[121 147 184]
  [118 144 181]
  [119 141 177]
  ..